export const documents = [
    { id: 0, name: "Passport", validfor: "Minimum 6 month validity" },
    { id: 1, name: "ENG1", validfor: "Every 2 years" },
    { id: 2, name: "STCW Proficiency in Fire Fighting & Fire Prevention", validfor: "2 years" },
    { id: 3, name: "STCW Proficiency in Personal Survival Techniques", validfor: "5 years" },
    { id: 4, name: "STCW Proficiency in Elementary First Aid", validfor: "5 years" },
    { id: 5, name: "STCW Proficiency in Personal Safety & Social Responsibilities", validfor: "5 years" },
    { id: 6, name: "STCW Proficiency in Security Awareness / Designated Security Duties / Ships Security Officer", validfor: "5 years" },
    { id: 7, name: "STCW Advanced Fire Fighting", validfor: "5 years" },
    { id: 8, name: "STCW Proficiency in Medical First Aid", validfor: "5 years" },
    { id: 9, name: "STCW Proficiency in Medical Care", validfor: "5 years" },
    { id: 10, name: "STCW Proficiency in Survival Craft & Rescue Boats (PSCRB)", validfor: "5 years" },
    { id: 11, name: "Yachtmaster Offshore", validfor: "5 years" },
    { id: 12, name: "Yachtmaster Ocean", validfor: "5 years" },
    { id: 13, name: "MCA Approved Engine Course AEC", validfor: "5 years" },
    { id: 14, name: "GMDSS / GOC", validfor: "5 years" },
    { id: 15, name: "ECDIS Certificate / Training (if equipped with ECDIS bridge) ", validfor: "5 years" },
    { id: 16, name: "Flag State Endorsement / CEC", validfor: "5 years" },
    { id: 17, name: "Yacht Rating Certificate STCW II/4 & III/4", validfor: "5 years" },
    { id: 18, name: "Marine Engine Operators License MEOL", validfor: "5 years" },
    { id: 19, name: "Marine Engineers Operator License (MEOL Y)", validfor: "5 years" },
    { id: 20, name: "Food Hygiene & Safety Level 2 Certificate or equivalent ", validfor: "5 years" },
    { id: 21, name: "Ships Cook CoC", validfor: "5 years" },
    { id: 22, name: "Ships Cook Training", validfor: "5 years" },
    { id: 23, name: "NVQ Level II in Catering & Hospitality", validfor: "5 years" },
    { id: 24, name: "CV & References", validfor: "5 years" },
    { id: 25, name: "Yachtmaster Costal", validfor: "5 years" },
    { id: 26, name: "Chief Engineer STCW III/3 / Y4", validfor: "5 years" },
    { id: 27, name: "Master CoC <500GT", validfor: "None" },
    { id: 28, name: "OOW (officer of the watch) Yachts CoC <3000GT", validfor: "None" },
    { id: 29, name: "Chief Engineer CoC STCW III/2 Y3", validfor: "5 years" },
    { id: 30, name: "Engineer Coc STCW III/3 (Y4)", validfor: "5 years" },
    { id: 31, name: "Chief Mate Certificate of Competency (CoC) STCW II/2", validfor: "5 years" },
    { id: 32, name: "Yacht Rating Certificate STCW II/4 & III/4", validfor: "5 years" },
    { id: 33, name: "Approved Engine Manufacturers Course (Type Specific)", validfor: "5 years" },
  ];